# Generated by Django 3.2.7 on 2022-12-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('selected_day_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='Index de la journée sélectionnée')),
                ('patrol_start_time', models.TimeField(verbose_name='Heure de début de la tournée')),
                ('tolerated_time', models.TimeField(verbose_name='Temps toléré')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Anomalie')),
                ('patrol_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patrollog', verbose_name='Journal de la tournée')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone', verbose_name='Zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
