# Generated by Django 3.2.7 on 2022-12-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_planning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='patrol_log',
        ),
        migrations.AddField(
            model_name='planning',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tag', verbose_name='Tag'),
        ),
    ]
