# Generated by Django 3.2.7 on 2022-12-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221226_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='tag',
        ),
    ]
