# Generated by Django 3.2.7 on 2022-12-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_planning_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='tolerated_time',
            field=models.DurationField(verbose_name='Temps toléré'),
        ),
    ]
