# Generated by Django 3.2.7 on 2022-12-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_planning_tolerated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='selected_day_index',
            field=models.CharField(blank=True, choices=[('1', 'Samedi'), ('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=10, null=True),
        ),
    ]
