# Generated by Django 3.2.7 on 2022-12-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221226_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='selected_day_index',
            field=models.CharField(blank=True, choices=[('1', 'Samedi'), ('2', 'Dimanche'), ('3', 'Lundi'), ('4', 'Mardi'), ('5', 'Mercredi'), ('6', 'Jeudi'), ('7', 'Vendredi'), ('8', 'Jour férié')], max_length=10, null=True),
        ),
    ]
