# Generated by Django 3.2.7 on 2022-12-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_planning_selected_day_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='patrol_start_time',
            new_name='patrol_check_time',
        ),
    ]
