# Generated by Django 3.2.7 on 2023-01-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_patrol_start_time_planning_patrol_check_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='selected_day_index',
            field=models.IntegerField(choices=[('1', 'Samedi'), ('2', 'Dimanche'), ('3', 'Lundi'), ('4', 'Mardi'), ('5', 'Mercredi'), ('6', 'Jeudi'), ('7', 'Vendredi'), ('8', 'Jour férié')], default=1, editable=False),
            preserve_default=False,
        ),
    ]
