# Generated by Django 3.2.7 on 2023-01-15 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_planning_selected_day_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('designation', models.CharField(max_length=100, verbose_name='Désignation')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patrollog',
            name='check_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date / Heure prévue '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrollog',
            name='check_tolerance',
            field=models.DurationField( verbose_name='Tolérance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrollog',
            name='checked_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.employee', verbose_name='Controlé par'),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='checked_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date / Heure de passage'),
        ),
        migrations.AddField(
            model_name='planning',
            name='state',
            field=models.IntegerField(choices=[('1', 'Brouillon'), ('2', 'Validé')], default=1),
        ),
        migrations.AlterField(
            model_name='planning',
            name='selected_day_index',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche'), (8, 'Jours fériés')], editable=False),
        ),
        migrations.AlterField(
            model_name='planning',
            name='zone',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.zone', verbose_name='Zone'),
        ),
    ]
