# Generated by Django 3.2.7 on 2023-01-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230115_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='state',
        ),
    ]
