# Generated by Django 3.2.7 on 2023-01-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_planning_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='plan_state',
            field=models.IntegerField(choices=[(1, 'Brouillon'), (2, 'Validé')], default=1),
        ),
    ]
