# Generated by Django 3.2.7 on 2023-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_zone_plan_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='plan_state',
            field=models.IntegerField(choices=[(1, 'Brouillon'), (2, 'Validé')], default=1, editable=False),
        ),
    ]
