# Generated by Django 3.2.7 on 2023-01-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_zone_plan_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code_pin',
            field=models.CharField(default=0, max_length=6, verbose_name='Code PIN'),
            preserve_default=False,
        ),
    ]
