# Generated by Django 3.2.7 on 2023-01-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employee_code_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrollog',
            name='planning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planning', verbose_name='Planning'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code_pin',
            field=models.CharField(max_length=255, null=True, verbose_name='Code PIN'),
        ),
    ]
